Repository nextcloud/twofactor_gateway, pull requests merged in 2019-01, with the labels that each got.

#179 Improved admin and created user documentation.
  doc/Admin Documentation.md
  doc/User documentation.md
Labels: 3. to review

#178 Add Nextcloud 16 support, drop 14
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
Labels: 3. to review, enhancement, technical debt

#185 Add eCall SMS provider
  doc/Admin Documentation.md
  lib/Command/Configure.php
  lib/Service/Gateway/SMS/Provider/EcallSMS.php
  lib/Service/Gateway/SMS/Provider/EcallSMSConfig.php
  lib/Service/Gateway/SMS/Provider/ProviderFactory.php
Labels: 3. to review, enhancement

#189 remove invalid voipsms provider
  lib/Command/Configure.php
Labels: 3. to review, bug
